# Generated by Django 5.0.6 on 2024-07-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='street_address1',
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(default='', max_length=80),
        ),
    ]
