# Generated by Django 5.0.6 on 2024-07-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_order_street_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
