# Generated by Django 5.0.6 on 2024-07-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_remove_order_full_name_order_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
