# Generated by Django 5.0.6 on 2024-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_color_productcolors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolors',
            name='color',
        ),
        migrations.AddField(
            model_name='productcolors',
            name='color_name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
