# Generated by Django 5.0.6 on 2024-06-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productcolors_color_productcolors_color_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolors',
            old_name='color_name',
            new_name='colors',
        ),
    ]
