# Generated by Django 5.0.6 on 2024-06-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_color_name_productcolors_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolors',
            old_name='colors',
            new_name='color',
        ),
    ]
