# Generated by Django 5.0.6 on 2024-06-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_colors_productcolors_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
        migrations.DeleteModel(
            name='ProductColors',
        ),
    ]
